### Post Login
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "email":"kshitij2707@gmail.com",
    "password":"ks",
    "name":"Kshitij",
    "age":20,
    "address":"Kharghar"
}

### POST Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"kshitij2707@gmail.com",
    "password":"kshitij2707"
}

### Live server login
POST https://binary-veda-assignment.onrender.com/api/auth/login
Content-Type: application/json

{
    "email":"kshitij2707@gmail.com",
    "password":"kshitij2707"
}